(********************************************************)
(*           AUTOGENERATED FILE - DO NOT EDIT!          *)
(********************************************************)
(* Generated by: ocaml-protoc-plugin                    *)
(* https://github.com/andersfugmann/ocaml-protoc-plugin *)
(********************************************************)
(*
  Source: xenapi.proto
  Syntax: proto3
  Parameters:
    debug=false
    annot='[@@deriving show { with_path = false }, eq]'
    opens=[]
    int64_as_int=true
    int32_as_int=true
    fixed_as_int=false
    singleton_record=false
    prefix_output_with_package=false
*)
[@@@ocaml.alert "-protobuf"] (* Disable deprecation warnings for protobuf*)
(**/**)
module Runtime' = Ocaml_protoc_plugin [@@warning "-33"]
module Imported'modules = struct
end
(**/**)
module rec Network_operations : sig
  type t =
    | Attaching
  [@@deriving show { with_path = false }, eq]
  val name: unit -> string
  (** Fully qualified protobuf name of this enum *)

  (**/**)
  val to_int: t -> int
  val from_int: int -> t Runtime'.Result.t
  val from_int_exn: int -> t
  val to_string: t -> string
  val from_string_exn: string -> t
  (**/**)
end = struct
  module This'_ = Network_operations
  type t =
    | Attaching
  [@@deriving show { with_path = false }, eq]
  let name () = ".network_operations"
  let to_int = function
    | Attaching -> 0
  let from_int_exn = function
    | 0 -> Attaching
    | n -> Runtime'.Result.raise (`Unknown_enum_value n)
  let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
  let to_string = function
    | Attaching -> "attaching"
  let from_string_exn = function
    | "attaching" -> Attaching
    | s -> Runtime'.Result.raise (`Unknown_enum_name s)

end

and Network_default_locking_mode : sig
  type t =
    | Unlocked
    | Disabled
  [@@deriving show { with_path = false }, eq]
  val name: unit -> string
  (** Fully qualified protobuf name of this enum *)

  (**/**)
  val to_int: t -> int
  val from_int: int -> t Runtime'.Result.t
  val from_int_exn: int -> t
  val to_string: t -> string
  val from_string_exn: string -> t
  (**/**)
end = struct
  module This'_ = Network_default_locking_mode
  type t =
    | Unlocked
    | Disabled
  [@@deriving show { with_path = false }, eq]
  let name () = ".network_default_locking_mode"
  let to_int = function
    | Unlocked -> 0
    | Disabled -> 1
  let from_int_exn = function
    | 0 -> Unlocked
    | 1 -> Disabled
    | n -> Runtime'.Result.raise (`Unknown_enum_value n)
  let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
  let to_string = function
    | Unlocked -> "unlocked"
    | Disabled -> "disabled"
  let from_string_exn = function
    | "unlocked" -> Unlocked
    | "disabled" -> Disabled
    | s -> Runtime'.Result.raise (`Unknown_enum_name s)

end

and Network_purpose : sig
  type t =
    | Nbd
    | Insecure_nbd
  [@@deriving show { with_path = false }, eq]
  val name: unit -> string
  (** Fully qualified protobuf name of this enum *)

  (**/**)
  val to_int: t -> int
  val from_int: int -> t Runtime'.Result.t
  val from_int_exn: int -> t
  val to_string: t -> string
  val from_string_exn: string -> t
  (**/**)
end = struct
  module This'_ = Network_purpose
  type t =
    | Nbd
    | Insecure_nbd
  [@@deriving show { with_path = false }, eq]
  let name () = ".network_purpose"
  let to_int = function
    | Nbd -> 0
    | Insecure_nbd -> 1
  let from_int_exn = function
    | 0 -> Nbd
    | 1 -> Insecure_nbd
    | n -> Runtime'.Result.raise (`Unknown_enum_value n)
  let from_int e = Runtime'.Result.catch (fun () -> from_int_exn e)
  let to_string = function
    | Nbd -> "nbd"
    | Insecure_nbd -> "insecure_nbd"
  let from_string_exn = function
    | "nbd" -> Nbd
    | "insecure_nbd" -> Insecure_nbd
    | s -> Runtime'.Result.raise (`Unknown_enum_name s)

end

and StringValue : sig
  type t = (string) [@@deriving show { with_path = false }, eq]
  (**
{%html:
<p>The string value.</p>
%}
  *)

  val make: ?value:string -> unit -> t
  (** Helper function to generate a message using default values *)

  val to_proto: t -> Runtime'.Writer.t
  (** Serialize the message to binary format *)

  val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
  (** Deserialize from binary format *)

  val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
  (** Serialize to Json (compatible with Yojson.Basic.t) *)

  val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
  (** Deserialize from Json (compatible with Yojson.Basic.t) *)

  val name: unit -> string
  (** Fully qualified protobuf name of this message *)

  (**/**)
  type make_t = ?value:string -> unit -> t
  val merge: t -> t -> t
  val to_proto': Runtime'.Writer.t -> t -> unit
  val from_proto_exn: Runtime'.Reader.t -> t
  val from_json_exn: Runtime'.Json.t -> t
  (**/**)
end = struct
  module This'_ = StringValue
  let name () = ".StringValue"
  type t = (string) [@@deriving show { with_path = false }, eq]
  type make_t = ?value:string -> unit -> t
  let make ?(value = {||}) () = (value)
  let merge =
  let merge_value = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "value", "value"), string, ({||})) ) in
  fun (t1_value) (t2_value) -> merge_value t1_value t2_value
  let spec () = Runtime'.Spec.( basic ((1, "value", "value"), string, ({||})) ^:: nil )
  let to_proto' =
    let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
    fun writer (value) -> serialize writer value

  let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
  let from_proto_exn =
    let constructor value = (value) in
    Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
  let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
  let to_json options =
    let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
    fun (value) -> serialize value
  let from_json_exn =
    let constructor value = (value) in
    Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
  let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
end

and Network : sig
  type t = {
    mTU:int;
    pIFs:string list;
    vIFs:string list;
    allowed_operations:Network_operations.t;
    assigned_ips:(string * string) list;
    blobs:(string * string) list;
    bridge:string;
    current_operations:(string * Network_operations.t) list;
    default_locking_mode:Network_default_locking_mode.t;
    managed:bool;
    name_description:string;
    name_label:string;
    other_config:(string * string) list;
    purpose:Network_purpose.t list;
    tags:string list;
    uuid:string;
  } [@@deriving show { with_path = false }, eq]
  val make: ?mTU:int -> ?pIFs:string list -> ?vIFs:string list -> ?allowed_operations:Network_operations.t -> ?assigned_ips:(string * string) list -> ?blobs:(string * string) list -> ?bridge:string -> ?current_operations:(string * Network_operations.t) list -> ?default_locking_mode:Network_default_locking_mode.t -> ?managed:bool -> ?name_description:string -> ?name_label:string -> ?other_config:(string * string) list -> ?purpose:Network_purpose.t list -> ?tags:string list -> ?uuid:string -> unit -> t
  (** Helper function to generate a message using default values *)

  val to_proto: t -> Runtime'.Writer.t
  (** Serialize the message to binary format *)

  val from_proto: Runtime'.Reader.t -> (t, [> Runtime'.Result.error]) result
  (** Deserialize from binary format *)

  val to_json: Runtime'.Json_options.t -> t -> Runtime'.Json.t
  (** Serialize to Json (compatible with Yojson.Basic.t) *)

  val from_json: Runtime'.Json.t -> (t, [> Runtime'.Result.error]) result
  (** Deserialize from Json (compatible with Yojson.Basic.t) *)

  val name: unit -> string
  (** Fully qualified protobuf name of this message *)

  (**/**)
  type make_t = ?mTU:int -> ?pIFs:string list -> ?vIFs:string list -> ?allowed_operations:Network_operations.t -> ?assigned_ips:(string * string) list -> ?blobs:(string * string) list -> ?bridge:string -> ?current_operations:(string * Network_operations.t) list -> ?default_locking_mode:Network_default_locking_mode.t -> ?managed:bool -> ?name_description:string -> ?name_label:string -> ?other_config:(string * string) list -> ?purpose:Network_purpose.t list -> ?tags:string list -> ?uuid:string -> unit -> t
  val merge: t -> t -> t
  val to_proto': Runtime'.Writer.t -> t -> unit
  val from_proto_exn: Runtime'.Reader.t -> t
  val from_json_exn: Runtime'.Json.t -> t
  (**/**)
end = struct
  module This'_ = Network
  let name () = ".network"
  type t = {
    mTU:int;
    pIFs:string list;
    vIFs:string list;
    allowed_operations:Network_operations.t;
    assigned_ips:(string * string) list;
    blobs:(string * string) list;
    bridge:string;
    current_operations:(string * Network_operations.t) list;
    default_locking_mode:Network_default_locking_mode.t;
    managed:bool;
    name_description:string;
    name_label:string;
    other_config:(string * string) list;
    purpose:Network_purpose.t list;
    tags:string list;
    uuid:string;
  } [@@deriving show { with_path = false }, eq]
  type make_t = ?mTU:int -> ?pIFs:string list -> ?vIFs:string list -> ?allowed_operations:Network_operations.t -> ?assigned_ips:(string * string) list -> ?blobs:(string * string) list -> ?bridge:string -> ?current_operations:(string * Network_operations.t) list -> ?default_locking_mode:Network_default_locking_mode.t -> ?managed:bool -> ?name_description:string -> ?name_label:string -> ?other_config:(string * string) list -> ?purpose:Network_purpose.t list -> ?tags:string list -> ?uuid:string -> unit -> t
  let make ?(mTU = 0) ?(pIFs = []) ?(vIFs = []) ?(allowed_operations = Network_operations.from_int_exn 0) ?(assigned_ips = []) ?(blobs = []) ?(bridge = {||}) ?(current_operations = []) ?(default_locking_mode = Network_default_locking_mode.from_int_exn 0) ?(managed = false) ?(name_description = {||}) ?(name_label = {||}) ?(other_config = []) ?(purpose = []) ?(tags = []) ?(uuid = {||}) () = { mTU; pIFs; vIFs; allowed_operations; assigned_ips; blobs; bridge; current_operations; default_locking_mode; managed; name_description; name_label; other_config; purpose; tags; uuid }
  let merge =
  let merge_mTU = Runtime'.Merge.merge Runtime'.Spec.( basic ((1, "MTU", "MTU"), int64_int, (0)) ) in
  let merge_pIFs = Runtime'.Merge.merge Runtime'.Spec.( repeated ((2, "PIFs", "PIFs"), string, not_packed) ) in
  let merge_vIFs = Runtime'.Merge.merge Runtime'.Spec.( repeated ((3, "VIFs", "VIFs"), string, not_packed) ) in
  let merge_allowed_operations = Runtime'.Merge.merge Runtime'.Spec.( basic ((4, "allowed_operations", "allowedOperations"), (enum (module Network_operations)), (Network_operations.from_int_exn 0)) ) in
  let merge_assigned_ips = Runtime'.Merge.merge Runtime'.Spec.( map ((5, "assigned_ips", "assignedIps"), (string, basic ((2, "value", "value"), string, ({||})))) ) in
  let merge_blobs = Runtime'.Merge.merge Runtime'.Spec.( map ((6, "blobs", "blobs"), (string, basic ((2, "value", "value"), string, ({||})))) ) in
  let merge_bridge = Runtime'.Merge.merge Runtime'.Spec.( basic ((7, "bridge", "bridge"), string, ({||})) ) in
  let merge_current_operations = Runtime'.Merge.merge Runtime'.Spec.( map ((8, "current_operations", "currentOperations"), (string, basic ((2, "value", "value"), (enum (module Network_operations)), (Network_operations.from_int_exn 0)))) ) in
  let merge_default_locking_mode = Runtime'.Merge.merge Runtime'.Spec.( basic ((9, "default_locking_mode", "defaultLockingMode"), (enum (module Network_default_locking_mode)), (Network_default_locking_mode.from_int_exn 0)) ) in
  let merge_managed = Runtime'.Merge.merge Runtime'.Spec.( basic ((10, "managed", "managed"), bool, (false)) ) in
  let merge_name_description = Runtime'.Merge.merge Runtime'.Spec.( basic ((11, "name_description", "nameDescription"), string, ({||})) ) in
  let merge_name_label = Runtime'.Merge.merge Runtime'.Spec.( basic ((12, "name_label", "nameLabel"), string, ({||})) ) in
  let merge_other_config = Runtime'.Merge.merge Runtime'.Spec.( map ((13, "other_config", "otherConfig"), (string, basic ((2, "value", "value"), string, ({||})))) ) in
  let merge_purpose = Runtime'.Merge.merge Runtime'.Spec.( repeated ((14, "purpose", "purpose"), (enum (module Network_purpose)), packed) ) in
  let merge_tags = Runtime'.Merge.merge Runtime'.Spec.( repeated ((15, "tags", "tags"), string, not_packed) ) in
  let merge_uuid = Runtime'.Merge.merge Runtime'.Spec.( basic ((16, "uuid", "uuid"), string, ({||})) ) in
  fun t1 t2 -> {
  	mTU = (merge_mTU t1.mTU t2.mTU);
  	pIFs = (merge_pIFs t1.pIFs t2.pIFs);
  	vIFs = (merge_vIFs t1.vIFs t2.vIFs);
  	allowed_operations = (merge_allowed_operations t1.allowed_operations t2.allowed_operations);
  	assigned_ips = (merge_assigned_ips t1.assigned_ips t2.assigned_ips);
  	blobs = (merge_blobs t1.blobs t2.blobs);
  	bridge = (merge_bridge t1.bridge t2.bridge);
  	current_operations = (merge_current_operations t1.current_operations t2.current_operations);
  	default_locking_mode = (merge_default_locking_mode t1.default_locking_mode t2.default_locking_mode);
  	managed = (merge_managed t1.managed t2.managed);
  	name_description = (merge_name_description t1.name_description t2.name_description);
  	name_label = (merge_name_label t1.name_label t2.name_label);
  	other_config = (merge_other_config t1.other_config t2.other_config);
  	purpose = (merge_purpose t1.purpose t2.purpose);
  	tags = (merge_tags t1.tags t2.tags);
  	uuid = (merge_uuid t1.uuid t2.uuid);
   }
  let spec () = Runtime'.Spec.( basic ((1, "MTU", "MTU"), int64_int, (0)) ^:: repeated ((2, "PIFs", "PIFs"), string, not_packed) ^:: repeated ((3, "VIFs", "VIFs"), string, not_packed) ^:: basic ((4, "allowed_operations", "allowedOperations"), (enum (module Network_operations)), (Network_operations.from_int_exn 0)) ^:: map ((5, "assigned_ips", "assignedIps"), (string, basic ((2, "value", "value"), string, ({||})))) ^:: map ((6, "blobs", "blobs"), (string, basic ((2, "value", "value"), string, ({||})))) ^:: basic ((7, "bridge", "bridge"), string, ({||})) ^:: map ((8, "current_operations", "currentOperations"), (string, basic ((2, "value", "value"), (enum (module Network_operations)), (Network_operations.from_int_exn 0)))) ^:: basic ((9, "default_locking_mode", "defaultLockingMode"), (enum (module Network_default_locking_mode)), (Network_default_locking_mode.from_int_exn 0)) ^:: basic ((10, "managed", "managed"), bool, (false)) ^:: basic ((11, "name_description", "nameDescription"), string, ({||})) ^:: basic ((12, "name_label", "nameLabel"), string, ({||})) ^:: map ((13, "other_config", "otherConfig"), (string, basic ((2, "value", "value"), string, ({||})))) ^:: repeated ((14, "purpose", "purpose"), (enum (module Network_purpose)), packed) ^:: repeated ((15, "tags", "tags"), string, not_packed) ^:: basic ((16, "uuid", "uuid"), string, ({||})) ^:: nil )
  let to_proto' =
    let serialize = Runtime'.apply_lazy (fun () -> Runtime'.Serialize.serialize (spec ())) in
    fun writer { mTU; pIFs; vIFs; allowed_operations; assigned_ips; blobs; bridge; current_operations; default_locking_mode; managed; name_description; name_label; other_config; purpose; tags; uuid } -> serialize writer mTU pIFs vIFs allowed_operations assigned_ips blobs bridge current_operations default_locking_mode managed name_description name_label other_config purpose tags uuid

  let to_proto t = let writer = Runtime'.Writer.init () in to_proto' writer t; writer
  let from_proto_exn =
    let constructor mTU pIFs vIFs allowed_operations assigned_ips blobs bridge current_operations default_locking_mode managed name_description name_label other_config purpose tags uuid = { mTU; pIFs; vIFs; allowed_operations; assigned_ips; blobs; bridge; current_operations; default_locking_mode; managed; name_description; name_label; other_config; purpose; tags; uuid } in
    Runtime'.apply_lazy (fun () -> Runtime'.Deserialize.deserialize (spec ()) constructor)
  let from_proto writer = Runtime'.Result.catch (fun () -> from_proto_exn writer)
  let to_json options =
    let serialize = Runtime'.Serialize_json.serialize ~message_name:(name ()) (spec ()) options in
    fun { mTU; pIFs; vIFs; allowed_operations; assigned_ips; blobs; bridge; current_operations; default_locking_mode; managed; name_description; name_label; other_config; purpose; tags; uuid } -> serialize mTU pIFs vIFs allowed_operations assigned_ips blobs bridge current_operations default_locking_mode managed name_description name_label other_config purpose tags uuid
  let from_json_exn =
    let constructor mTU pIFs vIFs allowed_operations assigned_ips blobs bridge current_operations default_locking_mode managed name_description name_label other_config purpose tags uuid = { mTU; pIFs; vIFs; allowed_operations; assigned_ips; blobs; bridge; current_operations; default_locking_mode; managed; name_description; name_label; other_config; purpose; tags; uuid } in
    Runtime'.apply_lazy (fun () -> Runtime'.Deserialize_json.deserialize ~message_name:(name ()) (spec ()) constructor)
  let from_json json = Runtime'.Result.catch (fun () -> from_json_exn json)
end

module Network_class = struct
  module Create = struct
    let package_name = None
    let service_name = "Network_class"
    let method_name = "Create"
    let name = "/Network_class/Create"
    module Request = Network
    module Response = StringValue
  end

  let create =
    (module Network : Runtime'.Spec.Message with type t = Network.t ),
    (module StringValue : Runtime'.Spec.Message with type t = StringValue.t )

end


